# Generated by Django 5.2.6 on 2025-11-11 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0003_remove_book_available_remove_book_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(default='N/A', max_length=20),
        ),
    ]
